# Site settings
title: yono.co
author: Yusaku ONO

# Jekyll settings
markdown: redcarpet
redcarpet:
  extensions: ['tables', 'autolink', 'no_intra_emphasis']
exclude: ['vendor', 'Gemfile', 'Gemfile.lock']
